### ISSUE TITLE
RDAirplay Add button segfault (v2.15.0 - QT4 - Ubuntu 16.04) 

### ISSUE THREAD

**Issue by Engineeringradio** [ElvishArtisan/rivendell#152]
RDAirplay is closing every time the Add button is pressed.

Extract from syslog:
`kernel: [   25.227348] rdairplay[1932]: segfault at 0 ip 00007f28b2bc4081 sp 00007fff779f2460 error 4 in librd-2.15.0.so[7f28b29cf000+472000]`

**Comment by rmc47** [comment]
Seeing the same thing, built from `master` @ 1bda51a91a84969e0d84a8bf44d180a4b3e168bf, Ubuntu MATE 16.04.2 LTS x64:

`rdairplay[89265]: segfault at 0 ip 00007f1e2020bb21 sp 00007ffe1d74ff40 error 4 in librd-2.15.0.so[7f1e20019000+46f000]`

Also see the same trying to use the _Select Log_ button:
`rdairplay[89308]: segfault at 0 ip 00007fb871e9db21 sp 00007fff4eaa36b0 error 4 in librd-2.15.0.so[7fb871cab000+46f000]`

@Engineeringradio did you get to the bottom of this at all?

**Comment by rmc47** [comment]
OK, dug into this a bit more: it was an inability to login because text validation was failing on empty password strings. On playing with that some more, I set a password, but noticed a segfault when backspacing in the password box of `rdlogin`. Fixed that in PR #177, I think, and now I can successfully set a user, add carts, and select a log.

**Comment by ElvishArtisan** [comment]
Fixed in v2.17.0.
