### ISSUE TITLE
(Master RPM Build) Problem with configure and "make rpm"

### ISSUE THREAD

**Issue by deltecent** [ElvishArtisan/rivendell#277]
1. /root/install_rivendell
2. /root/install_rivendell_devel
3. git clone
4. ./autogen.sh
5. ./configure
6. make rpm

```rivendell.spec``` will contain the following:
```
%build
%configure --libexecdir=${exec_prefix}/libexec --sysconfdir=${prefix}/etc
```
The ```make rpm``` will fail.

It seems ```configure``` must be called with ```--prefix=/usr --libdir=/usr/lib64 --libexecdir=/var/www/rd-bin --sysconfdir=/etc/httpd/conf.d``` or the RPM build will fail.

I don't now if this is by design or not or if ```rivendell.spec``` should be using these as defaults.

At a minimum I think ```rivendell.spec```, after running ```configure```, should contain:
```
%build
%configure --libexecdir=/usr/local/libexec --sysconfdir=/usr/local/etc
```

**Comment by ElvishArtisan** [comment]
You have to provide the proper arguments when invoking './configure' --e.g. ```./configure --prefix=/usr --libdir=/usr/lib64 --libexecdir=/var/www/rd-gin --sysconfdir=/etc/httpd/conf.d``` on RHEL. This is by design; specifically, it allows the 'make rpm' target to be used on non-RHEL systems --e.g. OpenSuSE -- that use RPM but have different data layouts (and hence require different arguments). The proposed default arguments will not result in a workable system on any platform of which I'm aware, so I don't see much point in asserting them.

We could, I suppose, arrange things so that running ./configure without any arguments throws a warning (perhaps with a pointer to some instructions, including some sample invocations for common platforms).
