### ISSUE TITLE
RDLibrary: '-- End of cart --' marker appears at the start of macro cart listing

### ISSUE THREAD

**Issue by ElvishArtisan** [ElvishArtisan/rivendell#293]
When editing a macro cart in rdlibrary(1), the '--- End of cart ---' marker appears as the *first* item in the listing rather than the last. AFAICT, the cart executes properly when touching the 'Run Cart' button.

**Comment by deltecent** [comment]
I saw that a while back. I have a change where there is no longer an --End of cart-- marker, since I found it unnecessary. It just lists the macos.  But I can also fix it where the marker is in the correct place.

**Comment by ElvishArtisan** [comment]
How does one append a new RML to the end of the stack without the marker?

**Comment by deltecent** [comment]
I just submitted a PR for this. It was there, and now it's gone. Let me know if I need to resubmit.

This is what GitHub was doing the other day when it was hosed. Their status page is showing errors again.

Patrick

**Comment by deltecent** [comment]
> How does one append a new RML to the end of the stack without the marker?

I just thought of the same thing while I was in the shower which is why I yanked by PR. I believe this is going to require a custom Q3ListViewItem::key() or Q3ListViewItem::compare() which currently extends beyond my C++ capabilities. But I'll get it figured out.

It looks like Qt3 sorted an empty field as greater than a number and Qt4 does the opposite.

**Comment by deltecent** [comment]
Pushed a PR that should take care of this problem.

**Comment by ElvishArtisan** [comment]
Fixed by 635a175.
