### ISSUE TITLE
(Master Bug/Feature) Dropbox changes require a restart

### ISSUE THREAD

**Issue by deltecent** [ElvishArtisan/rivendell#344]
I'm not sure if this is a bug or not (and I don't recall the behavior of 2.x), but when adding/removing/editing dropboxes in RDAdmin, Rivendell must be restarted before those changes take effect.

**Comment by deltecent** [comment]
SIGUSR1?

**Comment by ElvishArtisan** [comment]
That's definitely a bug. I will look into it today.

**Comment by ElvishArtisan** [comment]
Fixed in [master 9e93ddd]. I ended up refactoring the instance management to use the standard multicast notification channel.

The business with ```SIGUSR1``` is because dropbox instances are managed by rdserviced(8), which, as an intentionally 'dumb' process launcher, does not have access to multicast notifications. When it receives a ```SIGUSR1```, it shuts down all dropbox instances, re-reads the relevant records from the DROPBOXES table in the DB and then restarts things.

**Comment by ermina** [comment]
running 3.4.1 i encountered a probably related behavior:
- creating a dropbox in rdadmin does not spawn the relevant rdimport process.
- systemctl restart rivendell makes this rdimport process appear (but the restart hangs rdairplay processes using the dropbox host audio engine, so it is not really a solution for creating dropboxes on a production system)
