### ISSUE TITLE
Debian rules

### ISSUE THREAD

**Issue by wpope** [ElvishArtisan/rivendell#396]
Hi All
Has anyone in the group updated the Debian rules in the last 3 years to include rivendell 3.0 master with qt4 and debhelper >= 9
Walter

**Comment by ElvishArtisan** [comment]
The last update to 'debian/' was on 2009-08-04. There's been no identifiable Debian downstream maintainer since Tryphon ceased operations (and AFAICT even they were using their own local set of rules to build their debs), so I went ahead and removed the directory from the v3.x tree. 

I'd be glad to accept PRs to restore to restore and maintain same if someone would like to undertake the job.
