### ISSUE TITLE
Socket Errors and Process Hangs (rc02 - ARM)

### ISSUE THREAD

**Issue by bpm1992** [ElvishArtisan/rivendell#443]
Hello,
I've been seeing socket errors on Rivendell on the ARM architecture since the first 3.0 version which causes many of the command-line processes to hang.  The errors start to appear shortly after launching the daemons.    They seem to appear in most of the daemons.

RDAirPlay-20190604.log
04/06/2019 - 08:14:13.173 : received socket error 1

rdimport-20190604.log 
04/06/2019 - 08:20:48.740 : received socket error 0

RDLogManager-20190603.log
03/06/2019 - 19:02:22.542 : received socket error 0
03/06/2019 - 19:12:02.385 : received socket error 0
03/06/2019 - 19:13:55.467 : received socket error 0
03/06/2019 - 19:14:41.465 : received socket error 0
03/06/2019 - 19:17:15.945 : received socket error 0

**Comment by ElvishArtisan** [comment]
Known issue, possibly implicated in #425 as well. I've traced it down to a race in ```Q3Socket```. Since that class is part of the Qt3 support library in Qt4 (and hence slated eventually to be removed anyway), I've gone ahead and refactored the front-end connection handling code in caed(8) to eliminate all use of Q3Socket*. After cursory testing here, this does appear to have fixed the problem on ARM.

You can see current state of that work in the 'cae-rdsocket' branch. I am hoping to be merging this code to 'master' in the next day or so.

**Comment by ElvishArtisan** [comment]
> You can see current state of that work in the 'cae-rdsocket' branch. I am hoping to be merging this code to 'master' in the next day or so.

Done.

**Comment by ElvishArtisan** [comment]
Fixed in 64906f8.
