### ISSUE TITLE
Unable to generate the technical playout report

### ISSUE THREAD

**Issue by jangittelman** [ElvishArtisan/rivendell#525]
Rivendell version: 3.2.0
Database schema 311

The report creation window is missing the available host and services items.  The report does seem to get created, but is not available in rdlogmanager to be selected. Running the report from the command line (which worked in versions 2.19 and 1.7) produces and empty file.

<img width="458" alt="Screen Shot 2020-01-16 at 7 53 44 PM" src="https://user-images.githubusercontent.com/14166357/72575625-06007100-389b-11ea-9f83-92f0d135359e.png">

**Comment by radiocafero** [comment]
> I added it manually and the report works properly.
Hi! I have summary knowledge about mysql. Can you help me generate the correct rows for the reporting template? Thanks!

**Comment by jangittelman** [comment]
This is the kind of sql that I used to insert the row into REPORT_SERVICES:
INSERT INTO `REPORT_SERVICES` (`ID`, `REPORT_NAME`, `SERVICE_NAME`) VALUES (2,'RDAirPlayDailyPlayList','Production');

However, the missing service and host items in the report generation window is probably why the insert didn't happen. The service name couldn't be supplied.

**Comment by radiocafero** [comment]
Thank You!

Indeed. It works!

*MIRCEA  PAUN*
Project  Manager
+40 724232195
mircea.paun@radiocafe.ro
[image: cafelogo]
www.radiocafe.ro Casa Presei Libere, Bucharest.


Confidentiality Notice: This e-mail message, including any attachments, is
for the sole use of the intended recipient(s) and may contain confidential
and privileged information. Any unauthorized review, use, disclosure or
distribution of this information is prohibited, and may be punishable by
law. If this was sent to you in error, please notify the sender by reply
e-mail and destroy all copies of the original message. Please consider the
environment before printing this e-mail.

On 22 January 2020 at 23:50:48, jangittelman (notifications@github.com)
wrote:

This is the kind of sql that I used to insert the row into REPORT_SERVICES:
INSERT INTO REPORT_SERVICES (ID, REPORT_NAME, SERVICE_NAME) VALUES
(2,'RDAirPlayDailyPlayList','Production');

However, the missing service and host items in the report generation window
is probably why the insert didn't happen. The service name couldn't be
supplied.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/ElvishArtisan/rivendell/issues/525?email_source=notifications&email_token=AOLDMMHN7R7GCF3OXF7BZHLQ7C5TNA5CNFSM4KH7APWKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJVHOBI#issuecomment-577402629>,
or unsubscribe

**Comment by ElvishArtisan** [comment]
Fixed in ac59b52.
