### ISSUE TITLE
Bug: 4.14.03 Audio Science Driver Not Recognized 

### ISSUE THREAD

**Issue by philipbbeard** [ElvishArtisan/rivendell#55]
Our station is currently running Rivendell version 2.10.2 and freshly installed the 4.14.03 Audio Science HPI driver (from no previous Audio Science driver installed).  The driver module mounts fine on boot according to the syslogs and we can see the driver version displayed using rdhpiinfo but in the Audio Resources tab the card (ASI Card 5620) is not present under Audio Adaptors and the Audio HPI Driver displays "not active" under Supported Audio Drivers.  We've contacted the Audio Science support and they can't see any errors with the driver.  The asihpitest command executes correctly without displaying any errors and the Audio Science ALSA driver that comes compiled with the Ubuntu Kernel has been successfully blacklisted in accordance with the ASIHPI install documentation.

**Comment by edglazer** [comment]
Also worth noting that we are on Ubuntu 14.04, using the tryphon repositories to install Riv. We tried the stock drivers that come with Ubuntu (though you have to manually install 4.10.x firmware because 14.04 includes a regressed set of audioscience firmware), the hpklinux 4.14.03 ASI drivers, then removed the driver modules and firmware for 4.14.03, and finally compiled the hpklinux 4.10.26 ASI drivers to no avail. 

We also tried an older card, a 6044 with both the 4.13 and 4.10 driver branches. Consistent behavior across cards and driver versions. asihpitest functions, rdhpiinfo shows the cards, but going into Rdadmin > Manage Hosts > Edit Host > Audio Resources > and we see Supported Audioscience HPI [not active].

These drivers were compiled against kernel package version 3.13.0-32 if it makes any difference?

Any help is appreciated, as we're at a loss.

**Comment by edglazer** [comment]
We'll close this until we can verify it is definitely a Rivendell issue and not an issue with the Ubuntu or the Drivers in question.

**Comment by fabri8bit** [comment]
Problem driver on ubuntu:

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS ( 3.13.0-77-generic )
Release:	14.04
Codename:	trusty

dmesg | grep asihpi :

[   25.390839] snd_asihpi 0000:06:02.0: probe 104c:a106,175c:8900,0010
[   25.435851] snd_asihpi 0000:06:02.0: Incompatible firmware version DSP image 40E07 != Driver 40A01
[   25.467397] asihpi: module verification failed: signature and/or  required key missing - tainting kernel
[   25.468668] asihpi 0000:06:02.0: probe 104c:a106,175c:8900,0010
[   28.529250] asihpi 0000:06:02.0: Adapter at index 0 is not in low latency mode
[   28.529315] asihpi 0000:06:02.0: IRQs not supported by adapter at index 0
[   28.529318] asihpi 0000:06:02.0: using polled mode
[   28.529320] asihpi 0000:06:02.0: probe succeeded for ASI8921 HPI index 0

help me?
