### ISSUE TITLE
Macro Fun

### ISSUE THREAD

**Issue by Chester-Graham** [ElvishArtisan/rivendell#584]
If I insert a macro command 
PS 1 0!
in the main playing log it stops the cart immediately following it.
PS 1 5000! 
will start playing the cart immediately after it and then fade it in 5 seconds and stop.
Is this the intended behavior?
This is on Rivendell 3.4.0

**Comment by ElvishArtisan** [comment]
Yes.

Be aware that executing RMLs that modify log state ('Start Next' ['PN'], 'Stop' ['PS'], etc) in the same log machine that is being targeted can have counter-intuitive effects. That's because, in many situations, Rivendell's RML execution engine won't see the command until after macro cart sending the command has finished. Thus, it's often the _next_ event in the log that gets affected.

You'll generally get much more consistent results if you originate such commands from outside of the targeted log machine --e.g. another log machine, in response to a GPIO event, etc.

**Comment by Chester-Graham** [comment]
Thanks, I was afraid you were going to say that.
