### ISSUE TITLE
Database version conflict on 3.5.0:   346 vs 347

### ISSUE THREAD

**Issue by paulk-2** [ElvishArtisan/rivendell#643]
Symptom on remote workstation after upgrade to 3.5.0:
rdadmin, rdairplay, rdlibrary (etc) display "RDAdmin - Error, Database version mismatch, should be 347, is 346"

Setup:
Database host system is Centos 7
 Installed using "sudo yum install rivendell"  (updating from previous version)
 This system works fine including rdadmin, rdairplay, rdlibrary, etc.

Remote system is Raspberry Pi (Ubuntu)
 Compiled using instructions from http://wiki.rivendellaudio.org/index.php/Ubuntu18_04
 rd.conf 
 [mySQL]
; points to Centos 7 host system (not Raspberry Pi)  
Hostname=192.168.1.24

Research:
Looking through package, found many references to schema 346 which appear to be correct.
Found one reference to 347, which is intended for future version 3.6.0
Could not find source of problem.

apps will run with --skip-db-check option, but some apps can't see the database
apps that work:
rdlogin --skip-db-check    ; this launches, gets user name list ok (which shows it's getting to the database), appears to log user in.  but other apps have issues.
rdlogmanager --skip-db-check ;works ok

apps that do not work:
after logging in:
rdlibrary --skip-db-check  ;this does not show the user name, nor the group list (blank)
rdlogedit --skip-db-check ;shows empty log list

**Comment by edgeradio993fm** [comment]
Because you've cloned the master Rivendell git repo you've also got the latest planned updates to the database schema (347), which is a step ahead of the current production release and not compatible. It would be better to compile the 3.5.0 production release. Replace the "git clone -b master https://github.com/ElvishArtisan/rivendell.git" with the steps below.

```bash
wget https://github.com/ElvishArtisan/rivendell/releases/download/v3.5.0/rivendell-3.5.0.tar.gz

tar -xfv rivendell-3.5.0.tar.gz

cd rivendell-3.5.0
```
You can then move on to the ./autogen.sh step. Hope that solves your issues.

**Comment by paulk-2** [comment]
Thank you for the very helpful information.

I deleted previous "rivendell-3.5.0" and followed your instructions.  The apps no longer flag a database mismatch, but rdlibrary and rdlogedit do not display a user name (after running rdlogin and providing credentials).  rdlogin does display the user name list and gladly takes the password.

**Comment by edgeradio993fm** [comment]
I've seen this issue before. Trying to remember how I fixed it. I'm sure you done this, but remember to restart your system to make all new settings stick. A previous post from the mailing list suggested that deleting and re-adding users fixed it. I'm not so sure that'll help, but worth a try.

**Comment by paulk-2** [comment]
Yes, reboot fixed it.  

I want to fix the wiki, but when I tried to create an account it gave "Error sending mail:
Failed to connect to caspian.paravelsystems.com:25 [SMTP: Failed to connect socket: Permission denied (code: -1, response: )]".  I'll create a separate ticket.

The wiki page http://wiki.rivendellaudio.org/index.php/Ubuntu18_04 needs to be updated with your instructions.

Is there a way to update the rivendell.git page to show it's a separate version?  the docs show 3.5.0

Thank you for your kind help.

**Comment by edgeradio993fm** [comment]
No problem. Hope everything plays nice for your from now on.

Not sure who's in charge of the wiki nowadays. Hopefully someone will get back to you. The guide you used does suggest using production release rather than the latest git code. You're correct though, the guide should probably default to using a production release to avoid compatibility problems such as the one you encountered.

**Comment by ltyndale** [comment]
Hi,


I've updated the wiki to use the production release code as suggested.

Thanks,

Lorne Tyndale

**Comment by paulk-2** [comment]
Thank you!
