### ISSUE TITLE
Time Offset inconsistency in RDAirplay

### ISSUE THREAD

**Issue by kthelen** [ElvishArtisan/rivendell#647]
Possible issue spotted in 3.5.0 (installed via Paravel RPMs).

I've got a machine that's used to feed a satellite uplink. It takes audio 1.8 seconds to travel the path end to end. So I set that host's Time Offset in RDAdmin to +1800ms. Simple enough.

Comparing the RDAirplay clock display to the system clock, I see the offset is being utilized.

But timed starts in RDAirplay don't seem to affected by the offset; they still fire based on the system clock.

Am I not understanding how this feature works, or is this a possible bug?

**Comment by ElvishArtisan** [comment]
Yeesh, I had forgotten that this feature even existed.

A little bit of history:
This [mis-]feature was added back in 2004 (v.0.7.11!), in response to a very specific requirement from my then-employer. I've since come to the conclusion that the whole approach is a Really Bad Idea, mostly because displaying two different versions of the time (the real one, and the faux-Rivendell one) at the same time is a recipe for generating major confusion for the user. It only ever worked in rdairplay(1), and I haven't tested even there for over a decade. In short, it's a hack that shouldn't be relied upon and should (*will* be) removed from a future version of Rivendell.

I think the better approach would be build that time lag into your logs.
