### ISSUE TITLE
Date format and i18n

### ISSUE THREAD

**Issue by fpeyraud** [ElvishArtisan/rivendell#689]
Hi,
Currently, well, as of v3.6.1, date are represented as "`MM/dd/YYYY hh:mm:ss`" which is meaningful in some regions in the world, but very confusing in other regions, such as France, where I live. Moreover, it avoids sorting things by date which is quite a common usecase.
Would it be worth normalizing this to a standard format like [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) "`YYYY/mm/ddThh:mm:ss`"?

**Comment by druidlabs** [comment]
Plus one for this, but I suggest a config option to select US, European, or ISO display format, instead of a hard standardization on one over another.

A separate but interrelated request is to change Rivendell table displays so the date columns are sorted on the binary datetime (time_t?) value instead of the formatted date/time string.  So you don't have fun things like 5/31/2021 sorting before 5/3/2021.

**Comment by CWJR** [comment]
Another +1 here.

**Comment by edgeradio993fm** [comment]
+1 from me too. An option for a global date configuration would be amazing.

**Comment by druidlabs** [comment]
I'll note that the date _input_ fields should be updated as well as the _display_ fields.  Otherwise you get some nasty confusion between US and EU dates.

**Comment by ElvishArtisan** [comment]
Agreed. I'm thinking something along the lines of the following (see the [Metadata DateTime specification](http://opsguide.rivendellaudio.org/html/appendix.metadata_wildcards.html#table.metadata_wildcards.datetimes) for a description of the wildcards):

__Long Date Format__ - default format string: "DDDD, MMMM d yyyy"
Example: "Tuesday, December 28 2021"

__Short Date Format__ - default format string: "MM/dd/yy"
Example: "12/28/21"

__Time Format__ - default format string "hh:mm:ss"
Example: "13:23:21"

These format string values would be settable in RDAdmin->SystemSettings, and would provide a consistent formatting for date/time values throughout Rivendell instead of the current very American-centric hard-coded values.

The time values do have one broadcast-specific corner-case: for start times in logs, we provide precision down to one-tenth of a second, which the wildcards currently have no way to express. For that situation, I'm thinking that we could just take __Time Format__ and append the tenth value on to it.

Any other weird cases I'm missing?

**Comment by CWJR** [comment]
While we are on dates, it would be useful to us if the "Year Released" could be more granular.  If it could include month and day in addition to year, we would use it for music scheduling.

**Comment by ElvishArtisan** [comment]
> While we are on dates, it would be useful to us if the "Year Released" could be more granular. If it could include month and day in addition to year, we would use it for music scheduling.
That's a bit of a different issue. That 'year' field originally came from the CDDBv1 schema, which had resolution only to a year. MusicBrainz certainly has higher resolution, but we would need some way to differentiate the two.

**Comment by druidlabs** [comment]
> Any other weird cases I'm missing?

Well, it _is_ pretty far-fetched, but what about a multi-station system, where not all of the stations are in the same country?  You'd want the setting at the service level instead of system-wide. That scenario seems unlikely.

**Comment by ElvishArtisan** [comment]
'Kay, I've just implemented a first stab at this; see 15ff314. Implemented as system-wide settings. Mind you, none of this actually _does_ anything yet, but hopefully gives everyone an idea of where we're headed.

**Comment by ElvishArtisan** [comment]
Fully implemented as of e60d134.

I've added a 'DATE/TIME FORMATS' section to 'CODINGSTYLE', providing rationale, pointers and example code for implementing the standardized formats. Please test!

**Comment by ElvishArtisan** [comment]
No feedback in 30+ days, so I'm concluding that everything's perfect!  :innocent:

**Comment by fpeyraud** [comment]
Hi Fred. Sorry for the late answer. It looks perfect as you concluded;) Thanks !
