### ISSUE TITLE
RDLogManager/RDLogEdit Can't load carts

### ISSUE THREAD

**Issue by caryhon139** [ElvishArtisan/rivendell#706]
Version 4.0.0 Beta2. Clean install from source. Everything works except RDLogManager and RDLogEdit fail to load carts. RDLibrary displays a full directory of carts and the service is specified and valid. Might be something simple but I don't see it.

**Comment by caryhon139** [comment]
Noticed that RDLibrary lists the carts I imported via rdimport and they are listed in /var/snd. RDLogEdit and Manager can't find them.

**Comment by caryhon139** [comment]
[Errors.txt](https://github.com/ElvishArtisan/rivendell/files/7011698/Errors.txt)
Log files. /var/log/rivendell . Looks like a bad sql statement somwhere.

**Comment by alexolivan** [comment]
I'm experiencing a somehow related/similar issue, although I'm not sure it's the same, since Isee no SQL error on console, but rather Qt stuff errors causing the segfault.
The issue, but, happens precissely as I drag/drop carts/Macros in RDLogManager to setup an event.

To be more precisse, I have managed to create a first event, combining pre-import macro and carts, and post-import macros... overall, I tweaked a little the UI and noticed no issues.
The problem came as I tried to create a second Event. This is when segfaults happens.
The event itself IS persisted, and, aparently so are its properties (color, start type, segue...) but as soon as you try to drop a cart/macro at either pre or post import list, rdlogmanager crashes with following console output:

```
operador@debian:~$ rdlogmanager
QList::insert(): Index out of range.
QList::insert(): Index out of range.
QList::insert(): Index out of range.
QList::insert(): Index out of range.
QList::insert(): Index out of range.
Segmentation fault
```

**Comment by caryhon139** [comment]
It may be related. I ran logmanager from the system and added a pre-import cart into an event then ran through all the other screens and ended up generating a log filled with this cart. Everything added up ok. I just added a "select from" from a full library and then generated a log file. It worked. However, when I run my log generator script I get a bunch of errors, one for each cart being pulled. 

rd@Airplay-Studio:~/Desktop$ /usr/bin/rdlogmanager -g -d 0 -s CABC1 > ~/log1.txt
qt5ct: using qt5ct plugin
DB connection re-established
rdlogmanager: DB connection re-established
invalid SQL or failed DB connection[You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''CABC1-0822` && `LINK_ID`>=0 order by `LINK_ID` desc' at line 1 QMYSQL: Unable to execute query]: select `LINK_ID` from `LOG_LINES` where `LOG_NAME`='CABC1-0822` && `LINK_ID`>=0 order by `LINK_ID` desc

rdlogmanager: invalid SQL or failed DB connection[You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''CABC1-0822` && `LINK_ID`>=0 order by `LINK_ID` desc' at line 1 QMYSQL: Unable to execute query]: select `LINK_ID` from `LOG_LINES` where `LOG_NAME`='CABC1-0822` && `LINK_ID`>=0 order by `LINK_ID` desc

Now it seems that logedit sees all the carts and can import them into the existing log. Seems a convoluted way to generate a log. At least that seems to be the case until I reboot, which I will do now and test it out.

**Comment by caryhon139** [comment]
Now it works. Confusing.

**Comment by caryhon139** [comment]
Even more confusing, rdlogmanager is now working from a script where it wasn't before. I'm still getting a lot of sql code errors but it actually does generate a log.

**Comment by alexolivan** [comment]
I'm going to open a separate Issue because what I'm experiencing is, IMHO, frontend related (and there have been already some pesky issues due to migration/port of qt4 code to qt5) since I have no SQL error.
Also, because I'm stuck on 08/17 commits snapshot, and I'm worried that my code is drifting 'old'.

To this point, frontend error fixes have been promptly and effectively fixed... I would say they are, even if breaking some module's functionality entirelly, non-critical from core-code perspective 
SQL/backend errors tend to be, OTOH, a top priority thing to fix.

**Comment by ElvishArtisan** [comment]
So has #711 also fixed this?

**Comment by caryhon139** [comment]
Sorry. Dumb programmer here. Not sure how to install the fix. I messaged
someone I thought would know but he never replied.

_ Cary _

**Comment by ElvishArtisan** [comment]
No worries! I'm going to close this for now, but feel free to reopen if this recurs in the next beta.
