### ISSUE TITLE
RockyOS/EL8 repository

### ISSUE THREAD

**Issue by jeremielorente** [ElvishArtisan/rivendell#713]
Hi,
Do you plan to add a repository for RockyOS/EL8 as RedHat anounced the end of Centos 7/8 for the end of this year?
Regards

**Comment by ElvishArtisan** [comment]
Good question! While it wouldn't be particularly difficult, I've (thus far at least) been hearing extremely little call from the community RHEL 8 support. Is there anyone who would actually use this?

**Comment by jeremielorente** [comment]
So, for a fresh install, with axia driver, the best choice remains centos7? Even consudering the end of support? I hope community ask for el8 repo... Or fedora? :)

**Comment by ElvishArtisan** [comment]
RHEL 7 and UbuntuStudio LTS 20.02 (Focal Fossa) are the two distros for which I'm currently generating packages. For future, I'm planning to continue to build packages UbuntuStudio LTS. The situation with RHEL 8 and beyond is more cloudy. If there is some community demand, I can generate packages, but there'd be little point if there are no users (and the marginal costs in time and resources for adding an additional distro are non-trivial).

That said, one of the key goals for Rivendell v4.x is to work well on _all_ major Linux distros, even those for which there are no 'official' Paravel packages. (See for example #692, where we are currently addressing issues on Debian Bullseye as well as Raspbian)

**Comment by alexolivan** [comment]
Hi. I've some amount of confidence on my personal snapshot/nightly .deb packages build system, so I share here, since it may be useful for non-devel-skilled users to install and help the beta-test phase of rivendell qt5 on Debian distros (Buster, Bullseye and Bookworm)

The repo includes 'release' versions as well (build from release tarballs), so they can be targeted instead of 'snapshots' (latest commit).
glassplayer has still not a 'debianized' release tarball, so it is only in 'snapshots' distribution.
I've separated rivendell itself on its own component (main) from glassplayer/glasscoder (extras) and hpklinux (non-free)

Here it is:
[https://repo.alexolivan.com](https://repo.alexolivan.com)

**Comment by ElvishArtisan** [comment]
Done. Installation instructions available at [https://software.paravelsystems.com/howtos/rhel/8rd4/](https://software.paravelsystems.com/howtos/rhel/8rd4/).

Please test!
