### ISSUE TITLE
Cannot add content via RDLibrary

### ISSUE THREAD

**Issue by WMTH** [ElvishArtisan/rivendell#724]
After opening RDLibrary
![Screenshot at 2021-09-12 07-24-36](https://user-images.githubusercontent.com/8458996/132987593-8e580d33-1c8f-4ea9-8c48-e5530ace6c61.png)
selecting Add, the usual popup is displayed with each field preceded by a "&" and the fields editable.
![Screenshot at 2021-09-12 07-24-54](https://user-images.githubusercontent.com/8458996/132987662-537b48c0-501b-4219-b126-7037dd1fabc5.png)
Once the new edit box opens, it will be already populated with a cart which can de deleted or edited however none of the remaining buttons ( Import/Export, Rip CD, etc.) in the parent box are functional.
![Screenshot at 2021-09-12 07-25-16](https://user-images.githubusercontent.com/8458996/132987753-df28a24b-0606-409a-bb56-2c99861cb85a.png)

This behavior is observed in both CentOS 7 and Ubuntu builds (built form source or the Rivendell-built CentOS binary).

**Comment by ElvishArtisan** [comment]
Ah ha! Focus trouble...

The reason that none of the buttons are functional is because no cut in the cut list is selected. Click on the cut to select it, and the buttons will then work. 

Of course, as things currently stand, the UI is doing a very poor job of communicating this situation to the user, so I have just made the following changes:

1. Grey-out all disabled buttons, to make the fact that they are disabled obvious.
2. When creating a new audio cart, select the single cut automatically (and automatically "un-grey" the appropriate buttons to indicate this fact).
3. When opening an audio cart that contains one or more cuts, automatically select the first cut, but _only_ if that cut is currently valid for play-out. Otherwise, leave it deselected, so the user can observe its color.

Implemented in 7654811 and ce2321c. Please test!

**Comment by alexolivan** [comment]
Nice UI QoL improvement!

I would suggest, to keep that new functionality consistent in RDLibrary, to 'reset/refresh' the status of the edit / delete buttons on rdlibrary main screen as the filtering upper controls are manipulated.
So, if you select a new, group, scheduler code or whatever filtering, and the result yields a new empty list, or different list (any condition where no selected cart on the list is shown) then the buttons  get disabled again, so the user feels it can add a cart there if wanted, but can not start edit/delete actions until he/she picks a target item of the list first.

**Comment by WMTH** [comment]
Carts have been added successfully however, with new cuts, the Cut, Talk, and Segue markers cannot be altered (the columns are grayed-out).  Existing cuts (those brought over with the v3 database for test) can be altered in the usual way.

**Comment by alexolivan** [comment]
![Screenshot at 2021-09-13 13-59-02](https://user-images.githubusercontent.com/1419896/133079629-25d526a3-0340-4e1d-9da2-0a1ad657c1f3.png)
Right clicking on the waveform section spawns a menu to add new markers

**Comment by WMTH** [comment]
Got it, thank you for your assistance.
