### ISSUE TITLE
Cannot import .mp3 files via Dropbox in Ubuntu

### ISSUE THREAD

**Issue by WMTH** [ElvishArtisan/rivendell#725]
.mp3 files cannot be imported via a Dropbox in Ubuntu builds.  .wav files are imported normally.  This behavior is exhibited in Ubuntu builds only; import of .mp3 files in CentOS7 builds function normally.

**Comment by ElvishArtisan** [comment]
Unable to reproduce the problem here.

Some things to check in your setup:
1. After running './configure', you should be seeing the following line in the ```Audio Codecs``` section of the ```RIVENDELL CONFIGURATION SUMMARY```: ```MPEG Decoding Support ... Yes```.
2. Go into RDAdmin->ManageHosts->[hostname]->AudioResources and look in the 'SUPPORTED IMPORT FORMATS' section. You should see 'MPEG Layer 3' listed there.

If you're missing either of these items, then you're likely missing a dependency. The necessary packages for MP3 import support on Ubuntu are 'libmad0-dev' and 'libmad0`. If you're missing either of these, then install them and then re-configure and re-build Rivendell.

**Comment by WMTH** [comment]
I have traced this down and determined that if M4A support is included, the mp3 imports will fail with an "audio converter error" message.  Uninstalling faad-2 and mp4v2 code remediates the issue.  Notes:

1. The "--disable-mp4" flag is non-functional in configure
2. M4A support works in CentOS7 builds

**Comment by WMTH** [comment]
Downgraded mp4v2-2.1.0 to mp4v2-2.0.0, re-compiled Rivendell and problem remediated.
