### ISSUE TITLE
VU meter stop working after upgrade 

### ISSUE THREAD

**Issue by pandaradiocampus** [ElvishArtisan/rivendell#753]
Hi everyone
I will try to ask my issue again.
I was using rvdl 2.19, then I run un update to rvdl 3.6
After this update on my production machine the VU meters stop working and they doesn't display the sound level as expected and as it was before upgrade.

I read this thread https://github.com/ElvishArtisan/rivendell/issues/650#issuecomment-946847722
Dklann and I are using a huge amount of dropboxes on the malfunctionning machine, that'seems to be our common point.

I try to follow the walkthrough as described but there is something I don't uderstand what rd.conf should I modify (server or client) , and I can't find the lib/rdcae.cpp in the client machine.

I am a bit stuck. Can someone help me and sorry if I don't master the propper way to ask question.

**Comment by ElvishArtisan** [comment]
Got it. Much clearer, thanks.

To answer the simple question first: The changes to ```rd.conf(5)``` would be made on the same host as the [non-working] meters.

However, the code that eventuated from #650 (#653, a PR from @dklann) only made it into the v4.x codebase, and so is not available in v3.6. I do wonder though if this issue is the actual cause, as the metering code hasn't changed all that much between v2.19.3 and v3.6.2.

Let's try the following experiment:
1. Start the client Rivndell system as usual.
2. Get a root shell and enter the following command: `killall rdimport`.
3. Start a new instance of `rdlibrary(1)`, open an audio cart and try to play it. Do the meters work?

**Comment by pandaradiocampus** [comment]
> 
> 
> Got it. Much clearer, thanks.
> 
> To answer the simple question first: The changes to `rd.conf(5)` would be made on the same host as the [non-working] meters.
> 
> However, the code that eventuated from #650 (#653, a PR from @dklann) only made it into the v4.x codebase, and so is not available in v3.6. I do wonder though if this issue is the actual cause, as the metering code hasn't changed all that much between v2.19.3 and v3.6.2.
> 
> Let's try the following experiment:
> 
>     1. Start the client Rivndell system as usual.

done
> 
>     2. Get a root shell and enter the following command: `killall rdimport`.

done
> 
>     3. Start a new instance of `rdlibrary(1)`, open an audio cart and try to play it. Do the meters work?

My rdlibrary and my rdairplay works back again after killing the rdimport.

So I guess we have an issue with the big amount of dropboxes.

i there a simple method maybe to migrate all the dropboxes from one host to another?

Thank you for taking the time ti help me.

Should i restart the rdimport daemon ?

**Comment by dklann** [comment]
My experience has been that if you start RDAirplay *before* starting the dropboxes, the VU meters work (because they allocate the VU meter socket before they're all "used up"). Unfortunately, there's no simple way to delay startup of rdimport dropbox processes with the current Rivendell daemon architecture (using rdservice).

This would be possible if one were to configure the daemons (caed, ripcd, rdcatchd) as individual systemd services instead of using rdservice to start all three of them. But such a change would result in needing to make several other architectural changes ...

So, at this point, you're left with:
- normal startup
- manually terminate the dropboxes (e.g. `killall rdimport`)
- start RDAirplay
- restart the dropboxes (e.g.  `killall -USR1 rdservice`)

**Comment by pandaradiocampus** [comment]
yes this way seems to work well.
But can we do a script at startup with may be the same command as described upwards ?

Should i create an host to do the rdimport work  and another for the rdairplay ?

**Comment by dklann** [comment]
I guess it's up to you. Creating separate hosts for RDAirplay and dropbox-handling seems like a good idea to me.

**Comment by pandaradiocampus** [comment]
Ok this is what I'have done now, but is strange that the amount of dropboxes on my machine between v2.19 et v3.6 did'nt change and it stops the vumeters working.

**Comment by ElvishArtisan** [comment]
> My rdlibrary and my rdairplay VUmeters works back again after killing the rdimport.

That's pretty much a smoking gun that the problem _is_ socket exhaustion.

> Ok this is what IOk this is what I'have done now, but is strange that the amount of dropboxes on my machine between v2.19 et v3.6 did'nt change and it stops the vumeters working.'have done now, but is strange that the amount of dropboxes on my machine between v2.19 et v3.6 did'nt change and it stops the vumeters working.

Yes, it is a bit surprising. There's no arguing with data though!

**Comment by pandaradiocampus** [comment]
i guess i can close it. seems to be working.
