### ISSUE TITLE
RD4beta3 / RDLibrary - Edit Audio:  Cut Gain granularity

### ISSUE THREAD

**Issue by andrubemis** [ElvishArtisan/rivendell#774]
In RD3, the "Cut Gain" value in **RDLibrary - Edit Audio** is adjustable within two decimal points. In RD4, it displays only in integers. I know that it's stored to 100ths of a decibel within the database. Was there a reason for this to change between RD3 and RD4?

Perhaps I'm an exception, but I appreciate the greater granularity of RD3, especially since the database allows it.

**Comment by ElvishArtisan** [comment]
Being that most humans are incapable of perceiving a gain difference of less than roughly 3 dB, I think single dB resolution is adequate, not to mention far cleaner from a UI perspective. The DB stores it in 1/100th of a dB because that's how _all_ gain values are stored there. It's merely an internal convention in Rivendell, so one is not constantly having to remember "which unit is this gain in now?". A similar convention hold for time durations, which are always stored in the DB as milliseconds even though they rarely appear in the UI that way.
