### ISSUE TITLE
[question] IceCast status-json.xsl hasn't title

### ISSUE THREAD

**Issue by expertup** [ElvishArtisan/rivendell#821]
I have person with radio station. He has Rivendellaudio on Ubuntu and IceCast server. But status-json.xsl hasn't `title` song data in json result.

I think that this is problem with configuration, but I haven't idea where.

status-json.xsl:
```
{
   "icestats": {
      "admin": "icemaster@localhost",
      "host": "audio.example.com",
      "location": "Earth",
      "server_id": "Icecast 2.4.4",
      "server_start": "Fri, 09 Jul 2021 13:41:59 +0000",
      "server_start_iso8601": "2021-07-09T13:41:59+0000",
      "source": [
         {
         "audio_info": "channels=2;samplerate=48000;bitrate=256",
            "bitrate": 256,
            "channels": 2,
            "genre": "rock",
            "listener_peak": 4,
            "listeners": 0,
            "listenurl": "http://audio.example.com/mp3",
            "samplerate": 48000,
            "server_description": "Radio.com - MP3 256kbit/s",
            "server_name": "Radio",
            "server_type": "audio/mpeg",
            "server_url": "http://audio.example.com/",
            "stream_start": "Mon, 05 Sep 2022 23:37:46 +0000",
            "stream_start_iso8601": "2022-09-05T23:37:46+0000",
            "dummy": null
         },
         {
            "audio_info": "channels=2;samplerate=48000;bitrate=128",
            "bitrate": 128,
            "channels": 2,
            "genre": "rock",
            "listener_peak": 1,
            "listeners": 0,
            "listenurl": "http://audio.example.com/mp3-128",
            "samplerate": 48000,
            "server_description": "Radio.com - MP3 128kbit/s",
            "server_name": "Radio",
            "server_type": "audio/mpeg",
            "server_url": "http://audio.example.com/",
            "stream_start": "Mon, 05 Sep 2022 23:37:46 +0000",
            "stream_start_iso8601": "2022-09-05T23:37:46+0000",
            "dummy": null
         },
         {
            "audio_bitrate": 160000,
            "audio_channels": 2,
            "audio_info": "channels=2;samplerate=48000;bitrate=160",
            "audio_samplerate": 48000,
            "bitrate": 160,
            "channels": 2,
            "genre": "rock",
            "ice-bitrate": 160,
            "listener_peak": 0,
            "listeners": 0,
            "listenurl": "http://audio.example.com/ogg",
            "samplerate": 48000,
            "server_description": "Radio.com - Ogg 160kbit/s",
            "server_name": "Radio",
            "server_type": "application/ogg",
            "server_url": "http://audio.example.com/",
            "stream_start": "Mon, 05 Sep 2022 23:37:42 +0000",
            "stream_start_iso8601": "2022-09-05T23:37:42+0000",
            "subtype": "Vorbis",
            "dummy": null
         }
      ]
   }
}
```

![WhatsApp Image 2022-09-06 at 10 18 44](https://user-images.githubusercontent.com/1708687/188700459-0cce6bd7-ad2d-477e-9082-984c0e4b1407.jpeg)
![WhatsApp Image 2022-09-05 at 17 19 22](https://user-images.githubusercontent.com/1708687/188700464-5d4a4a69-66d3-4739-a05a-7b05d1c48963.jpeg)

**Comment by alexolivan** [comment]
Hi!

Icecast2 is a very straight-forward piece of server, rock solid, so, as long as you know the password to send/push metadata updates, you're good to go... so, what caught my attention is that in your screenshot, I see no active pypad script active/running (maybe you deleted just before the screenshot while you were testing).
I mean, in order to have pypad updating Icecast2 instance, you have to setup/activate an Icecast2 type/template script in the pypad manager, in which you will declare the right details to contact your Icecast server (host, port, and bind credentials)

Visualy, you'll expect something similar (but not necessarily same! I explain late) to this:
![Screenshot at 2022-09-07 09-44-16](https://user-images.githubusercontent.com/1419896/188821449-e947efdd-7c0e-4760-a7cb-d590bb6143a8.png)

Notice the green dot on the script entry on the pypad GUI manager, indicating the script is running successfully.
Also notice that the script contains the actual details of the stuff.

My setup but would differ from yours in that I'm using a glasscoder pypad script to update Icecast2 title at encoder level, whereas you want an icecast pypad script to update title directly at the server.
The difference between the two approaches is that, if you update the metadata title at encoder level, then audio and title will always be perfectly in sync, whereas if you update the title directly on the server, you may experience some 'gap', depending on the streaming delay, between metadata title change, and actual audio change.

My advice is to use Glasscoder, which is an incredible piece of software (also from Fred!), that is fully and nicelly integrated with Rivendell (supports multiple streams, formats, HLS... fully Rivendell integration... is the perfect choice):
![Screenshot at 2022-09-07 09-45-06](https://user-images.githubusercontent.com/1419896/188824523-e1f16ae4-e7fb-4a63-b734-abce26cc45d7.png)

Cheers!

**Comment by expertup** [comment]
Ok, it brightened up. But I have a question. Does the pypad script affect the audio stream? Can they overwrite it? Does it work independently?

https://github.com/ElvishArtisan/rivendell/blob/master/apis/pypad/scripts/pypad_icecast2.py
https://github.com/ElvishArtisan/rivendell/blob/master/apis/pypad/scripts/pypad_icecast2.exemplar

There is a "Mountpoint = /audio.mp3" parameter in "pypad_icecast2" - what is it about?

I am asking because Rivendell was set up by another person and I have no experience, and I would not like to spoil what works well so far.

**Comment by alexolivan** [comment]
ok... somehow off-topic from Rivendell itself (but rather on what I actually do at job :-P) but here we go :-)

Pypad script SHOULD NOT affect the audio (AFAIK ... I don't know its internals at code-level... but it should, and I bet does not). The script contacts/binds to the streaming server and notices it that the title metadata has changed to a new certain value... nothing else. It has nothing to do with audio.

Audio is fed to the server by means of an encoder device or software (such as glasscoder, butt, etc, etc).  

mountpoint? ... sure! ... unlike ancient stream servers (such the typical DNAS v1.9.8 , etc, etc) an Icecast server can host, multiple streams simultaneously, and server them as listener/clients choice:
For instance, a typical use-case scenario is one where you hace your radio station audio encoded in two different streams, on in mp3 format for high quality and maximum compatibilty, and one in HE-AAC format for maximum compression and mimimal bandwidth usage on the end listener, for mobile applications.
... So ... how do you identify each individual stream on a single server??? ---> mountpoints ;-)
Mountpoints are identifiers for streams on the Icecast server. Both for the encoding end (you need to know and define where your encoding ends up) and for the listening end (you need to know and define what audio to listen)

At this point, it should be logical to realize that pypad needs to know to which mountpoint of the icecast server it has to update the title metadata.
And therefore you have to match it with your encoding software settings... if you're encoding so you're bringing up the mountpoint /myfancyradio.mp3 , then, you have to setup pypad icecast2 script so it updates /myfancyradio.mp3 mountpoint.

Regarding back to your audio related question, now that mountpoints are presented, you should know that ONLY ONE AUDIO SOURCE can fed a mountpint... So there's never ever a chance of 'interference' regarding audio feeding.
If two encoders, with the right configuration, would try to feed the same mountpoint simultaneosly, only the first one of them will manage to bind and bring the mounpoint up. The second one will be rejected.

Hope the picture is cleare now.
Cheers

**Comment by expertup** [comment]
Ok, now is clear. I understand all :-) Thank You.

**Comment by ElvishArtisan** [comment]
> Pypad script SHOULD NOT affect the audio (AFAIK ... I don't know its internals at code-level... but it should, and I bet does not). The script contacts/binds to the streaming server and notices it that the title metadata has changed to a new certain value... nothing else. It has nothing to do with audio.

Assuming that you're using the ```pypad_icecast2``` plug-in, then no, it doesn't touch the audio at all; all it does is send an HTTP event to the IceCast server to notify it of the metadata update. If audio is being affected, then that would be due to an issue in the server. (Unlikely; as Alejandro mentioned upthread, IceCast has generally been a very stable piece of software).
