### ISSUE TITLE
RDCastmanager: Minor Front-end issue while deleting episodes

### ISSUE THREAD

**Issue by alexolivan** [ElvishArtisan/rivendell#893]
Found a minor issue on RDCastManager.
When deleting episodes on the edit feed tool, while the Fron-end nicely updates on the foreground window (Edit feed), the background window does only partially: Entries are deleted, but the tree structure is not updated (I bet yet another pesky qt5 annoyance), resulting in a kind of weird looking data structure:

![Screenshot at 2023-06-30 12-28-03](https://github.com/ElvishArtisan/rivendell/assets/1419896/14563313-372c-4680-a4c1-d33d360fa5ed)

Just an annoyance... but maybe it is an easy fix.

**Comment by ElvishArtisan** [comment]
Confirmed here.

**Comment by ElvishArtisan** [comment]
Ok, I'm throwing in the towel here. Turns out that properly fixing this is basically going to mean completely reimplementing the underlying data model for podcasts feeds. So, I've simply disabled the ability to display sublists of items in the main ```rdcastmanager(1)``` window. Call me lazy...

If anybody else wants to take a crack at this, feel free! The previous behavior can be reenabled by changing the ```RDTableView``` widget back to a ```RDTreeView```.
