### ISSUE TITLE
RMLSEND PX error

### ISSUE THREAD

**Issue by Chester-Graham** [ElvishArtisan/rivendell#901]
Centos 7 install following standard instructions, version 3.6.7 Schema 347
This command works . . . rmlsend PX\ 1\ 000002\!
This command fails . . . rmlsend PX\ 1\ 000002\ PLAY\!
This command fails . . .rmlsend PX\ 1\ 000002\ STOP\!
This command fails . . . rmlsend PX\ 1\ 000002\ play\!
This command fails . . .rmlsend PX\ 1\ 000002\ stop\!

**Comment by ElvishArtisan** [comment]
Try putting an offset value before the transition type. For example, instead of:

```rmlsend PX\ 1\ 000002\ PLAY!```

try:

```rmlsend PX\ 1\ 000002\ 0\ PLAY!```

The current [entry in the Operations Guide](https://opsguide.rivendellaudio.org/html/sect.rml.commands.html#sect.rml.insert_cart__px_) is actually in error here. It has the invocation as:
```PX mach cart [offset] [PLAY|SEGUE|STOP]!```
whereas it should be:
```PX mach cart [offset [PLAY|SEGUE|STOP]]!```

The transition type specification is case insensitive.

**Comment by ElvishArtisan** [comment]
Corrected in e47ef55. This correction will appear in the next regular release.

**Comment by Chester-Graham** [comment]
Thank you, I can confirm that both of these work.
"rmlsend PX\ 1\ 000002\ 0\ PLAY\!" (this one has a trailing slash that gets filtered out in this forum)
"rmlsend PX\ 1\ 000002\ 0\ PLAY!"
