### ISSUE TITLE
rdairplay - Generates SQL error every midnight during log rotate

### ISSUE THREAD

**Issue by tcbeaton** [ElvishArtisan/rivendell#93]
rdairplay: invalid SQL or failed DB connection[You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-15-09-01_LOG where COUNT=0' at line 1 QMYSQL3: Unable to execute query]: select TRANS_TYPE from G-15-09-01 where COUNT=0

rdairplay: Database connection failed : select TRANS_TYPE from G-15-09-01_LOG where COUNT=0

rdairplay: Database connection restored.

**Comment by ElvishArtisan** [comment]
On Nov 12, 2015, at 12:13 46, tcbeaton <notifications@github.com> wrote:

> rdairplay: invalid SQL or failed DB connection[You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-15-09-01_LOG where COUNT=0' at line 1 QMYSQL3: Unable to execute query]: select TRANS_TYPE from G-15-09-01 where COUNT=0

Known problem, already fixed in Git.  It will be in the next regular release.

Cheers!


|----------------------------------------------------------------------|
| Frederick F. Gleason, Jr. |              Chief Developer             |
|                           |              Paravel Systems             |
|----------------------------------------------------------------------|
|          A room without books is like a body without a soul.         |
|                                         -- Cicero                    |
|----------------------------------------------------------------------|

**Comment by tcbeaton** [comment]
Cool. :-)

Thanks,

Tom Beaton

**Comment by ElvishArtisan** [comment]
Fixed in v2.12.0.
