### ISSUE TITLE
rdlibrary hangs during cd ripping

### ISSUE THREAD

**Issue by flipmcf** [ElvishArtisan/rivendell#997]
Ubuntu 22.02 - wayland:

![image](https://github.com/user-attachments/assets/f94a5b0b-3942-4837-9f1e-65a06e3a830c)

Launch RD Library first. & click on "rip CD" to pull up the cd ripper

THEN, put in a CD.

This is probably just a blocking network call to MusicBrains, but Wayland (and other desktop environments) may think the application has locked up.

It will eventually work, even without clicking 'wait', but Ubuntu / Unity / Wayland / QT doesn't know that.

Can we get a spinning wheel and a cancel button maybe, rather than this user experience that may convince the user that something is broken?

**Comment by ElvishArtisan** [comment]
> This is probably just a blocking network call to MusicBrains

The calls to MusicBrainz / CDDB are completely asynchronous and should cause little to no perceptible delay to the UI (other than the user having to wait for the relevant data to populate in the track widget). Where it typically blocks hard is in a kernel ioctl, specifically ```CDROM_MEDIA_CHANGED```, which can take anywhere from a second or two to a couple dozen seconds to read the disc's TOC (depending on the state of the CD drive and condition of the disc). It's especially egregious if you have ```Read ISRCs from CD``` set to 'On' in RDAdmin->ManageHosts->RDLibrary and have loaded a CD that has no ISRC data encoded, because then, in addition to running that ioctl, the system will end up scanning the _entire_ CD (potentially up to 700 MB worth of data) before concluding "Nope, no ISRC data here!".

These operations block the entire process thread/event loop, so poll() and friends are not going to do much good. One could I suppose spawn an entirely separate process to run an 'I'm busy!' message, but that's a pretty heavy lift. Pthreads won't help you there as the the GUI classes in Qt are not thread-safe. Perhaps an entirely separate 'helper' program to go fetch the relevant data from the drive and then report back? (See 'utils/rdselect_helper/' for an example).

**Comment by glenndrives** [comment]
Perhaps a quick check from RDLibrary when the Rip CD button is pressed to verify a CD is present?


We haven't had this problem, our users are trained to insert the CD before trying to rip.


Cheers!


Glenn L. Hickman Jr.
Director, Radio Frequency Engineering

[WHRO Public Media]<https://www.whro.org/>

5200 Hampton Boulevard | Norfolk, VA 23508
P:757-575-5064
whro.org


________________________________

**Comment by ElvishArtisan** [comment]
Unfortunately, the only way to get that information is by calling that self-same ```CDROM_MEDIA_CHANGED``` ioctl. And then wait for the response.

**Comment by ElvishArtisan** [comment]
Although, the more I think about it, the more the "helper program" concept sounds viable. It wouldn't actually speed anything up (the optical drive will take however long it takes to get things done), but it would keep the UI from freezing, which would certainly make things _feel_ more responsive.
